version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
#  server:
#    build: ./server
#    privileged: true
#    volumes:
#      - ./server:/server
#    environment:
#      - NODE_ENV=development
#    working_dir: /server
#    command: sh -c "yarn install && yarn dev"
#    ports:
#      - '3000:3000'
#  app:
#    image: node:12.12
#    volumes:
#      - .:/app
#    environment:
#      - NODE_ENV=development
#    working_dir: /app
#    command: sh -c "yarn install && yarn web"
#    ports:
#      - '8080:8080'
volumes:
    mongo:
